[package]
name = "buffer-srv-example"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
gfx = "0.16"
gfx_window_glutin = "0.17"
gfx_device_gl = "0.14"
glutin = "0.9"

